default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: store_mcomputers_development

test:
  <<: *default
  database: store_mcomputers_test

production:
  <<: *default
  database: store_mcomputers_production
  username: store_mcomputers
  password: <%= ENV['STORE_MCOMPUTERS_DATABASE_PASSWORD'] %>
